# version: "3.9"
services:
  demos-app:
    container_name: demos-app
    build: .
    restart: unless-stopped
    volumes:
      - ./instance/.claude:/home/app/.claude
      - ./instance:/instance
    ports:
      - "8000:8000"
  # demos-caddy:
  #   container_name: demos-caddy
  #   image: caddy:2-alpine
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - caddy_data:/data
  #     - caddy_config:/config
volumes: {}
  # caddy_data:
  # caddy_config:
